image:
  file: /gitpod/Dockerfile

tasks:
  - init: |
      curl -fsSL https://pkgs.tailscale.com/stable/debian/bullseye.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
      curl -fsSL https://pkgs.tailscale.com/stable/debian/bullseye.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list
      sudo apt-get update
      sudo apt-get install docker.io
      sudo apt-get install tailscale
  - name: dotfiles
    command: |
      if [ ! -d "~/.dotfiles" ]; then
        cd /tmp
        curl -sSL https://raw.githubusercontent.com/gbraad/dotfiles/master/install.sh -o /tmp/install.sh &&
        rm -f ~/.zshrc &&
        sh /tmp/install.sh
      fi
      mv ~/.bashrc-nochsh ~/.bashrc
  - name: sshd
    command: |
      sudo ssh-keygen -A && sudo /usr/sbin/sshd
      curl https://github.com/gbraad.keys | tee -a ~/.ssh/authorized_keys

ports:
  - port: 22
    onOpen: ignore
  - port: 6080
    onOpen: open-preview

vscode:
  extensions:
    - ms-vscode.Theme-TomorrowKit
