ARG BASE_VERSION="bookworm"

FROM ghcr.io/gbraad-devenv/debian/dotfiles:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/debian"

USER root

RUN apt-get update \
    && apt-get install -y \
        systemd \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/sbin/init"]
