ARG BASE_IMAGE="ghcr.io/gbraad-devenv/debian/dotfiles"
ARG BASE_VERSION="bookworm"

FROM ${BASE_IMAGE}:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/debian"

USER root

# already 'enabled' by default
#RUN systemctl enable tailscaled

ENTRYPOINT ["/sbin/init"]
