ARG BASE_IMAGE="ghcr.io/gbraad-dotfiles/debian"
ARG BASE_VERSION="bookworm"

FROM ${BASE_IMAGE}:${BASE_VERSION} AS base

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/debian"

USER root

RUN apt-get update \
    && apt-get install -y \
        wget \
        openssh-client \
        openssh-server \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get install -y \
        tmux \
        screen \
        zssh \
    && rm -rf /var/lib/apt/lists/*

COPY assets/tailscaled /etc/init.d/tailscaled

RUN curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg -o /etc/apt/keyrings/githubcli-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
    && apt update \
    && apt install -y \
        gh \
    && rm -rf /var/lib/apt/lists/*
