ARG BASE_IMAGE="ghcr.io/gbraad-devenv/debian/rebase"
ARG BASE_VERSION="bookworm"

FROM ${BASE_IMAGE}:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/debian"

USER gbraad

ENTRYPOINT [ "/bin/zsh" ]
