ARG BASE_VERSION="bookworm"

FROM ghcr.io/gbraad-devenv/debian/base:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/debian"

RUN git clone https://github.com/gbraad/dotfiles ~/.dotfiles \
    && ~/.dotfiles/install.sh

ENTRYPOINT [ "/bin/zsh" ]
