ARG BASE_VERSION="bookworm"

FROM ghcr.io/gbraad-devenv/debian/dotfiles:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/debian"

USER root

# already 'enabled' by default
#RUN systemctl enable tailscaled

ENTRYPOINT ["/sbin/init"]
