FROM ghcr.io/gbraad-devenv/debian/base:bookworm

USER root

# for distrobox
RUN apt-get update \
    && apt-get install -y \
        zsh \
        apt-utils \
        bc \
        curl \
        dialog \
        diffutils \
        findutils \
        gnupg2 \
        less \
        libnss-myhostname \
        libvte-2.9[0-9]-common \
        libvte-common \
        lsof \
        ncurses-base \
        passwd \
        pinentry-curses \
        procps \
        sudo \
        time \
        wget \
        util-linux \
    && apt-get install -y \
        libegl1-mesa \
        libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*
