FROM ghcr.io/gbraad-devenv/debian/dotfiles:bookworm

USER root

RUN apt-get update \
    && apt-get install -y \
        systemd \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/sbin/init"]
CMD ["/sbin/init"]
