FROM debian:bullseye

RUN apt-get update \
    && apt-get install -y \
        git \
        sudo \
        openssh-client \
        openssh-server \
        curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://pkgs.tailscale.com/stable/debian/bullseye.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null \
    && curl -fsSL https://pkgs.tailscale.com/stable/debian/bullseye.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list \
    && sudo apt-get update \
    && sudo apt-get install -y \
        docker.io \
        tailscale \
        stow \
        zsh \
        screen \
        tmux \
        powerline \
        zssh \
    && rm -rf /var/lib/apt/lists/*

COPY scripts/tailscaled /etc/init.d/tailscaled
RUN mkdir -p /var/run/tailscale /var/cache/tailscale /var/lib/tailscale
